=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Cars.dtd
<!ELEMENT car (manufacturer_bg, manufacturer_en, model, year_of_production, body_type, powertrain, acceleration, maximum_speed, fuel_tank_volume, chassi, number_of_doors, number_of_seats, kerb_weight, length, width, height, features)>
    
        <!ELEMENT manufacturer_bg (#PCDATA)>
        
        <!ELEMENT manufacturer_en (#PCDATA)>
        
        <!ELEMENT model (#PCDATA)>
            <!ATTLIST model generation CDATA #IMPLIED>
        
        <!ELEMENT year_of_production (#PCDATA)>
        
        <!ELEMENT body_type (#PCDATA)>
        
        <!ELEMENT powertrain (engine, transmission)>
            <!ELEMENT engine (power, torque, capacity, consumption, emissions)>
                <!ATTLIST engine fuel CDATA #REQUIRED>               
                <!ATTLIST engine number_of_cylinders CDATA #REQUIRED>
                <!ATTLIST engine position CDATA #REQUIRED>
                
                <!ELEMENT power (#PCDATA)>
                    <!ATTLIST power units CDATA #IMPLIED>
                    
                <!ELEMENT torque (#PCDATA)>
                    <!ATTLIST torque units CDATA #IMPLIED>
                    <!ATTLIST torque at CDATA #IMPLIED>
                    
                <!ELEMENT capacity (#PCDATA)>
                    <!ATTLIST capacity units CDATA #IMPLIED>
                
                <!ELEMENT consumption (#PCDATA)>
                    <!ATTLIST consumption units CDATA #IMPLIED>
                    <!ATTLIST consumption type CDATA #IMPLIED>
                    
                <!ELEMENT emissions (#PCDATA)>
                    <!ATTLIST emissions units CDATA #IMPLIED>
                    <!ATTLIST emissions class CDATA #IMPLIED>
                    
            <!ELEMENT transmission (#PCDATA)>
                <!ATTLIST transmission number_of_gears CDATA #REQUIRED>
                
        <!ELEMENT acceleration (#PCDATA)>
            <!ATTLIST acceleration units CDATA #IMPLIED>
            <!ATTLIST acceleration type CDATA #IMPLIED>
        
        <!ELEMENT maximum_speed (#PCDATA)>
            <!ATTLIST maximum_speed units CDATA #IMPLIED>
        
        <!ELEMENT fuel_tank_volume (#PCDATA)>
            <!ATTLIST fuel_tank_volume units CDATA #IMPLIED>
            
        <!ELEMENT chassi (front_suspension, rear_suspension, front_brakes, rear_brakes)>
            <!ELEMENT front_suspension (#PCDATA)>
            <!ELEMENT rear_suspension (#PCDATA)>
            <!ELEMENT front_brakes (#PCDATA)>
            <!ELEMENT rear_brakes (#PCDATA)>
        
        <!ELEMENT number_of_doors (#PCDATA)>

        <!ELEMENT number_of_seats (#PCDATA)>
        
        <!ELEMENT kerb_weight (#PCDATA)>
            <!ATTLIST kerb_weight units CDATA #IMPLIED>
        
        <!ELEMENT length (#PCDATA)>
            <!ATTLIST length units CDATA #IMPLIED>
        
        <!ELEMENT width (#PCDATA)>
            <!ATTLIST width units CDATA #IMPLIED>
        
        <!ELEMENT height (#PCDATA)>
            <!ATTLIST height units CDATA #IMPLIED>
        
        <!ELEMENT features (feature)+>
            <!ELEMENT feature (#PCDATA)>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Хонда</manufacturer_bg>
    <manufacturer_en>Honda</manufacturer_en>
    <model generation = "7-ма">Сивик</model>        
    <year_of_production>2001</year_of_production>
    <body_type>Хечбек</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position="отзад">
            <power units = "конски сили">200</power>
            <torque units = "нютон метри" at="5900об/мин">196</torque>
            <capacity units = "см3">1998</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">8.9</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО4">212</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">6.8</acceleration>
    <maximum_speed units = "км/ч">235</maximum_speed>
    <fuel_tank_volume units = "литри">50</fuel_tank_volume>
    <chassi>
        <front_suspension>амортисьорна стойка</front_suspension>
        <rear_suspension>напречен стабилизатор</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>3</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1200</kerb_weight>
    <length units = "мм">4135</length>
    <width units = "мм">1695</width>
    <height units = "мм">1425</height>
    <features>
        <feature>Антиблокираща система</feature>        
        <feature>Електрически странични огледала</feature>
        <feature>Имобилайзер</feature>       
        <feature>Спортно окачване</feature>
        <feature>Спортни седалки</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Ферари</manufacturer_bg>
    <manufacturer_en>Ferrari</manufacturer_en>
    <model generation = "Италия">458</model>        
    <year_of_production>2009</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "8" position="отзад">
            <power units = "конски сили">570</power>
            <torque units = "нютон метри" at="6000об/мин">540</torque>
            <capacity units = "см3">4497</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">13.3</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">307</emissions>
        </engine>
        <transmission number_of_gears = "7">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">3.4</acceleration>
    <maximum_speed units = "км/ч">325</maximum_speed>
    <fuel_tank_volume units = "литри">86</fuel_tank_volume>
    <chassi>
        <front_suspension>многолостово независимо окачване</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>2</number_of_seats>
    <kerb_weight units = "кг.">1380</kerb_weight>
    <length units = "мм">4527</length>
    <width units = "мм">1937</width>
    <height units = "мм">1213</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>Алармена система</feature>
        <feature>Климатроник</feature>
        <feature>Блутут</feature>            
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument17.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Лексус</manufacturer_bg>
    <manufacturer_en>Lexus</manufacturer_en>
    <model generation = "ЛФА" >ЛФА</model>        
    <year_of_production>2010</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "10" position="отпред">
            <power units = "конски сили">560</power>
            <torque units = "нютон метри" at="6800об/мин">480</torque>
            <capacity units = "см3">4805</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">19.6</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">379</emissions>
        </engine>
        <transmission number_of_gears = "6">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">3.7</acceleration>
    <maximum_speed units = "км/ч">326</maximum_speed>
    <fuel_tank_volume units = "литри">73</fuel_tank_volume>
    <chassi>
        <front_suspension>двоен напречен носач</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>2</number_of_seats>
    <kerb_weight units = "кг.">1480</kerb_weight>
    <length units = "мм">4505</length>
    <width units = "мм">1895</width>
    <height units = "мм">1220</height>
    <features>
        <feature>Антиблокираща система</feature>                        
        <feature>Климатроник</feature>         
        <feature>Тракшън-контрол</feature>
        <feature>Отопление на седалките</feature>
        <feature>Ел. седалки</feature>
        <feature>Парктроник</feature>
        <feature>Сензор за дъжд</feature>
        <feature>Навигация</feature>
        <feature>Темпомат</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Фолксваген</manufacturer_bg>
    <manufacturer_en>Volkswagen</manufacturer_en>
    <model generation = "ССI" >Пасат</model>        
    <year_of_production>2012</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "6" position="отпред">
            <power units = "конски сили">300</power>
            <torque units = "нютон метри" at = "2400-5300об/мин">350</torque>
            <capacity units = "см3">3597</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">9.2</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">215</emissions>
        </engine>
        <transmission number_of_gears = "6">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">5.5</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">70</fuel_tank_volume>
    <chassi>
        <front_suspension>независимо пружинно тип McPherson със стабилизатор</front_suspension>
        <rear_suspension>винтова пружина</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1704</kerb_weight>
    <length units = "мм">4802</length>
    <width units = "мм">1855</width>
    <height units = "мм">1417</height>
    <features>
        <feature>Антиблокираща система</feature>                        
        <feature>Климатроник</feature>                        
        <feature>4x4</feature>           
        <feature>Сензор за дъжд</feature>
        <feature>Ел. стъкла</feature>
        <feature>Спортни седалки</feature>
        <feature>Спортно окачване</feature>
        <feature>Отопление на седалките</feature>
        <feature>Система - асистент при паркиране</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Сензор за светлина</feature>
        <feature>Старт-стоп система</feature>
    </features>        
</car>
