=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Cars.dtd
<!ELEMENT car (manufacturer_bg, manufacturer_en, model, year_of_production, body_type, powertrain, acceleration, maximum_speed, fuel_tank_volume, chassi, number_of_doors, number_of_seats, kerb_weight, length, width, height, features)>
    
        <!ELEMENT manufacturer_bg (#PCDATA)>
        
        <!ELEMENT manufacturer_en (#PCDATA)>
        
        <!ELEMENT model (#PCDATA)>
            <!ATTLIST model generation CDATA #IMPLIED>
        
        <!ELEMENT year_of_production (#PCDATA)>
        
        <!ELEMENT body_type (#PCDATA)>
        
        <!ELEMENT powertrain (engine, transmission)>
            <!ELEMENT engine (power, torque, capacity, consumption, emissions)>
                <!ATTLIST engine fuel CDATA #REQUIRED>               
                <!ATTLIST engine number_of_cylinders CDATA #REQUIRED>
                <!ATTLIST engine position CDATA #REQUIRED>
                
                <!ELEMENT power (#PCDATA)>
                    <!ATTLIST power units CDATA #IMPLIED>
                    
                <!ELEMENT torque (#PCDATA)>
                    <!ATTLIST torque units CDATA #IMPLIED>
                    <!ATTLIST torque at CDATA #IMPLIED>
                    
                <!ELEMENT capacity (#PCDATA)>
                    <!ATTLIST capacity units CDATA #IMPLIED>
                
                <!ELEMENT consumption (#PCDATA)>
                    <!ATTLIST consumption units CDATA #IMPLIED>
                    <!ATTLIST consumption type CDATA #IMPLIED>
                    
                <!ELEMENT emissions (#PCDATA)>
                    <!ATTLIST emissions units CDATA #IMPLIED>
                    <!ATTLIST emissions class CDATA #IMPLIED>
                    
            <!ELEMENT transmission (#PCDATA)>
                <!ATTLIST transmission number_of_gears CDATA #REQUIRED>
                
        <!ELEMENT acceleration (#PCDATA)>
            <!ATTLIST acceleration units CDATA #IMPLIED>
            <!ATTLIST acceleration type CDATA #IMPLIED>
        
        <!ELEMENT maximum_speed (#PCDATA)>
            <!ATTLIST maximum_speed units CDATA #IMPLIED>
        
        <!ELEMENT fuel_tank_volume (#PCDATA)>
            <!ATTLIST fuel_tank_volume units CDATA #IMPLIED>
            
        <!ELEMENT chassi (front_suspension, rear_suspension, front_brakes, rear_brakes)>
            <!ELEMENT front_suspension (#PCDATA)>
            <!ELEMENT rear_suspension (#PCDATA)>
            <!ELEMENT front_brakes (#PCDATA)>
            <!ELEMENT rear_brakes (#PCDATA)>
        
        <!ELEMENT number_of_doors (#PCDATA)>

        <!ELEMENT number_of_seats (#PCDATA)>
        
        <!ELEMENT kerb_weight (#PCDATA)>
            <!ATTLIST kerb_weight units CDATA #IMPLIED>
        
        <!ELEMENT length (#PCDATA)>
            <!ATTLIST length units CDATA #IMPLIED>
        
        <!ELEMENT width (#PCDATA)>
            <!ATTLIST width units CDATA #IMPLIED>
        
        <!ELEMENT height (#PCDATA)>
            <!ATTLIST height units CDATA #IMPLIED>
        
        <!ELEMENT features (feature)+>
            <!ELEMENT feature (#PCDATA)>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Мерцедес</manufacturer_bg>
    <manufacturer_en>Mercedes</manufacturer_en>
    <model generation = "6-та" >С63</model>        
    <year_of_production>2013</year_of_production>
    <body_type>Седан</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "8" position="отпред">
            <power units = "конски сили">585</power>
            <torque units = "нютон метри" at="2250-3750об/мин">900</torque>
            <capacity units = "см3">5461</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">10.1</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО6">244</emissions>
        </engine>
        <transmission number_of_gears = "7">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">70</fuel_tank_volume>
    <chassi>
        <front_suspension>независимо многолостово</front_suspension>
        <rear_suspension>независимо многолостово</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>4</number_of_seats>
    <kerb_weight units = "кг.">2045</kerb_weight>
    <length units = "мм">5116</length>
    <width units = "мм">1899</width>
    <height units = "мм">1496</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>            
        <feature>Четиризонов климатроник</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Безключово палене</feature>
        <feature>Система за измиване на фаровете</feature>
        <feature>Ел. регулиране на седалките</feature>
        <feature>Система - асистент при паркиране</feature>
        <feature>Система от камери 360*</feature>
        <feature>Система за контрол на скоростта(автопилот)</feature>            
        <feature>Bluetooth \ handsfree система</feature>           
        <feature>Автоматичен контрол на стабилността</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Порше</manufacturer_bg>
    <manufacturer_en>Porsche</manufacturer_en>
    <model generation = "991 II">911</model>        
    <year_of_production>2015</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "6" position="отзад">
            <power units = "конски сили">580</power>
            <torque units = "нютон метри" at="2250-4000об/мин">750</torque>
            <capacity units = "см3">3800</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">9.1</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО6">212</emissions>
        </engine>
        <transmission number_of_gears = "7">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">2.9</acceleration>
    <maximum_speed units = "км/ч">330</maximum_speed>
    <fuel_tank_volume units = "литри">68</fuel_tank_volume>
    <chassi>
        <front_suspension>независимо тип McPherson</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>4</number_of_seats>
    <kerb_weight units = "кг.">1600</kerb_weight>
    <length units = "мм">4507</length>
    <width units = "мм">1880</width>
    <height units = "мм">1297</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>4x4</feature>
        <feature>Климатроник</feature>
        <feature>Круиз контрол</feature>
        <feature>Система - асистент при паркиране</feature>
        <feature>Сензор за дъжд</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Спортно окачване</feature>
        <feature>Спортни седалки</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>БМВ</manufacturer_bg>
    <manufacturer_en>BMW</manufacturer_en>
    <model generation = "ф10">М5</model>        
    <year_of_production>2011</year_of_production>
    <body_type>Седан</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "8" position="отпред">
            <power units = "конски сили">560</power>
            <torque units = "нютон метри" at="1500-5750об/мин">680</torque>
            <capacity units = "см3">4395</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">9.9</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">234</emissions>
        </engine>
        <transmission number_of_gears = "7">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.3</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">80</fuel_tank_volume>
    <chassi>
        <front_suspension>двоен напречен носач</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1870</kerb_weight>
    <length units = "мм">4910</length>
    <width units = "мм">1891</width>
    <height units = "мм">1457</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>Система за контрол на скоростта(автопилот) - Круиз контрол</feature>
        <feature>Четиризонов климатроник</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Безключово палене</feature>
        <feature>Система за измиване на фаровете</feature>
        <feature>Система - асистент при паркиране</feature>                       
        <feature>Система за подпомагане на спирането</feature>
        <feature>Ел. регулиране на окачването</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Бентли</manufacturer_bg>
    <manufacturer_en>Bentley</manufacturer_en>
    <model generation = "ГТ 2" >Континентал</model>        
    <year_of_production>2015</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "12" position="отпред">
            <power units = "конски сили">590</power>
            <torque units = "нютон метри" at="1700об/мин">720</torque>
            <capacity units = "см3">5998</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">14.2</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО6">330</emissions>
        </engine>
        <transmission number_of_gears = "8">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.5</acceleration>
    <maximum_speed units = "км/ч">319</maximum_speed>
    <fuel_tank_volume units = "литри">90</fuel_tank_volume>
    <chassi>
        <front_suspension>двоен напречен носач</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>4</number_of_seats>
    <kerb_weight units = "кг.">2320</kerb_weight>
    <length units = "мм">4806</length>
    <width units = "мм">1944</width>
    <height units = "мм">1404</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>            
        <feature>Климатроник</feature>
        <feature>Камера в помощ на паркирането</feature>
        <feature>Отопление на седалките</feature>
        <feature>Устройство "свободни ръце"</feature>
        <feature>Фарове за мъгла</feature>
        <feature>Светлини за завиване</feature>        
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Ауди</manufacturer_bg>
    <manufacturer_en>Audi</manufacturer_en>
    <model generation = "Б7">РС4</model>        
    <year_of_production>2006</year_of_production>
    <body_type>Седан</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "8" position = "отпред">
            <power units = "конски сили">420</power>
            <torque units = "нютон метри" at = "5500об/мин">430</torque>
            <capacity units = "см3">4163</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">13.4</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО4">326</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.8</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">63</fuel_tank_volume>
    <chassi>
        <front_suspension>независимо многолостово</front_suspension>
        <rear_suspension>независимо окачване на трапецовидни носачи</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1650</kerb_weight>
    <length units = "мм">4589</length>
    <width units = "мм">1816</width>
    <height units = "мм">1415</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>Круиз контрол</feature>
        <feature>Куатро</feature>
        <feature>Двузонов климатроник</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Система - асистент при паркиране</feature>            
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Субару</manufacturer_bg>
    <manufacturer_en>Subaru</manufacturer_en>
    <model generation = "3">Импреза</model>        
    <year_of_production>2008</year_of_production>
    <body_type>Хечбек</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position="отпред">
            <power units = "конски сили">330</power>
            <torque units = "нютон метри" at="3400об/мин">470</torque>
            <capacity units = "см3">2457</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">10.3</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО4">243</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.8</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">60</fuel_tank_volume>
    <chassi>
        <front_suspension>няколко носача и щанги</front_suspension>
        <rear_suspension>няколко носача и щанги</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1535</kerb_weight>
    <length units = "мм">4415</length>
    <width units = "мм">1740</width>
    <height units = "мм">1475</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>Темпомат</feature>
        <feature>Климатроник</feature>
        <feature>Навигация</feature>       
        <feature>Спортни седалки</feature>
        <feature>Фарове за мъгла</feature>               
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Митсубиши</manufacturer_bg>
    <manufacturer_en>Mitsubishi</manufacturer_en>
    <model generation = "Еволюшън 10" >Лансер</model>        
    <year_of_production>2007</year_of_production>
    <body_type>Седан</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position="отпред">
            <power units = "конски сили">295</power>
            <torque units = "нютон метри" at="3500об/мин">366</torque>
            <capacity units = "см3">1997</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">10.5</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">243</emissions>
        </engine>
        <transmission number_of_gears = "5">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.8</acceleration>
    <maximum_speed units = "км/ч">274</maximum_speed>
    <fuel_tank_volume units = "литри">55</fuel_tank_volume>
    <chassi>
        <front_suspension>амортисьорна стойка</front_suspension>
        <rear_suspension>напречен носач</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1560</kerb_weight>
    <length units = "мм">4505</length>
    <width units = "мм">1810</width>
    <height units = "мм">1480</height>
    <features>
        <feature>Антиблокираща система</feature>                        
        <feature>Климатроник</feature>                        
        <feature>4x4</feature>           
        <feature>Сензор за дъжд</feature>
        <feature>Ел. стъкла</feature>
        <feature>Спортни седалки</feature>
        <feature>Спортно окачване</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Ауди</manufacturer_bg>
    <manufacturer_en>Audi</manufacturer_en>
    <model generation = "Д4">С8</model>        
    <year_of_production>2012</year_of_production>
    <body_type>Седан</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "8" position="отпред">
            <power units = "конски сили">520</power>
            <torque units = "нютон метри" at="1700-5500об/мин">650</torque>
            <capacity units = "см3">3993</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">10.1</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">235</emissions>
        </engine>
        <transmission number_of_gears = "8">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.2</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">90</fuel_tank_volume>
    <chassi>
        <front_suspension>многолостово окачване</front_suspension>
        <rear_suspension>независимо окачване на трапецовидни носачи</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1975</kerb_weight>
    <length units = "мм">5146</length>
    <width units = "мм">1949</width>
    <height units = "мм">1458</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>4x4</feature>
        <feature>Климатроник</feature>
        <feature>Круиз контрол</feature>
        <feature>Система - асистент при паркиране</feature>
        <feature>Сензор за дъжд</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Спортно окачване</feature>
        <feature>Спортни седалки</feature>
        <feature>Сензор за светлина</feature>
        <feature>Старт-стоп система</feature>
        <feature>Електронен контрол на стабилността</feature>
    </features>        
</car>
