=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Cars.dtd
<!ELEMENT car (manufacturer_bg, manufacturer_en, model, year_of_production, body_type, powertrain, acceleration, maximum_speed, fuel_tank_volume, chassi, number_of_doors, number_of_seats, kerb_weight, length, width, height, features)>
    
        <!ELEMENT manufacturer_bg (#PCDATA)>
        
        <!ELEMENT manufacturer_en (#PCDATA)>
        
        <!ELEMENT model (#PCDATA)>
            <!ATTLIST model generation CDATA #IMPLIED>
        
        <!ELEMENT year_of_production (#PCDATA)>
        
        <!ELEMENT body_type (#PCDATA)>
        
        <!ELEMENT powertrain (engine, transmission)>
            <!ELEMENT engine (power, torque, capacity, consumption, emissions)>
                <!ATTLIST engine fuel CDATA #REQUIRED>               
                <!ATTLIST engine number_of_cylinders CDATA #REQUIRED>
                <!ATTLIST engine position CDATA #REQUIRED>
                
                <!ELEMENT power (#PCDATA)>
                    <!ATTLIST power units CDATA #IMPLIED>
                    
                <!ELEMENT torque (#PCDATA)>
                    <!ATTLIST torque units CDATA #IMPLIED>
                    <!ATTLIST torque at CDATA #IMPLIED>
                    
                <!ELEMENT capacity (#PCDATA)>
                    <!ATTLIST capacity units CDATA #IMPLIED>
                
                <!ELEMENT consumption (#PCDATA)>
                    <!ATTLIST consumption units CDATA #IMPLIED>
                    <!ATTLIST consumption type CDATA #IMPLIED>
                    
                <!ELEMENT emissions (#PCDATA)>
                    <!ATTLIST emissions units CDATA #IMPLIED>
                    <!ATTLIST emissions class CDATA #IMPLIED>
                    
            <!ELEMENT transmission (#PCDATA)>
                <!ATTLIST transmission number_of_gears CDATA #REQUIRED>
                
        <!ELEMENT acceleration (#PCDATA)>
            <!ATTLIST acceleration units CDATA #IMPLIED>
            <!ATTLIST acceleration type CDATA #IMPLIED>
        
        <!ELEMENT maximum_speed (#PCDATA)>
            <!ATTLIST maximum_speed units CDATA #IMPLIED>
        
        <!ELEMENT fuel_tank_volume (#PCDATA)>
            <!ATTLIST fuel_tank_volume units CDATA #IMPLIED>
            
        <!ELEMENT chassi (front_suspension, rear_suspension, front_brakes, rear_brakes)>
            <!ELEMENT front_suspension (#PCDATA)>
            <!ELEMENT rear_suspension (#PCDATA)>
            <!ELEMENT front_brakes (#PCDATA)>
            <!ELEMENT rear_brakes (#PCDATA)>
        
        <!ELEMENT number_of_doors (#PCDATA)>

        <!ELEMENT number_of_seats (#PCDATA)>
        
        <!ELEMENT kerb_weight (#PCDATA)>
            <!ATTLIST kerb_weight units CDATA #IMPLIED>
        
        <!ELEMENT length (#PCDATA)>
            <!ATTLIST length units CDATA #IMPLIED>
        
        <!ELEMENT width (#PCDATA)>
            <!ATTLIST width units CDATA #IMPLIED>
        
        <!ELEMENT height (#PCDATA)>
            <!ATTLIST height units CDATA #IMPLIED>
        
        <!ELEMENT features (feature)+>
            <!ELEMENT feature (#PCDATA)>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Нисан</manufacturer_bg>
    <manufacturer_en>Nissan</manufacturer_en>
    <model generation = "ГТР фейслифт">ГТР</model>        
    <year_of_production>2011</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "6" position="отзад">
            <power units = "конски сили">530</power>
            <torque units = "нютон метри" at="3200-6000об/мин">612</torque>
            <capacity units = "см3">3799</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">12</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">279</emissions>
        </engine>
        <transmission number_of_gears = "6">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">3.1</acceleration>
    <maximum_speed units = "км/ч">315</maximum_speed>
    <fuel_tank_volume units = "литри">74</fuel_tank_volume>
    <chassi>
        <front_suspension>двоен напречен носач</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>4</number_of_seats>
    <kerb_weight units = "кг.">1740</kerb_weight>
    <length units = "мм">4670</length>
    <width units = "мм">1895</width>
    <height units = "мм">1370</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>        
        <feature>Климатроник</feature>
        <feature>Темпомат</feature>
        <feature>Фарове за мъгла</feature>
        <feature>Спортно окачване</feature>
        <feature>Навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Устройство "свободни ръце"</feature> 
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>БМВ</manufacturer_bg>
    <manufacturer_en>BMW</manufacturer_en>
    <model generation = "Е52">З8</model>        
    <year_of_production>2000</year_of_production>
    <body_type>Кабриолет</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "8" position="отпред">
            <power units = "конски сили">400</power>
            <torque units = "нютон метри" at="3800об/мин">500</torque>
            <capacity units = "см3">4941</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">14.5</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО3">358</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">4.7</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">73</fuel_tank_volume>
    <chassi>
        <front_suspension>амортисьорна стойка</front_suspension>
        <rear_suspension>винтова пружина</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>2</number_of_seats>
    <kerb_weight units = "кг.">1660</kerb_weight>
    <length units = "мм">4400</length>
    <width units = "мм">1830</width>
    <height units = "мм">1317</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>      
        <feature>Климатик</feature>        
        <feature>Отопление на седалките</feature>
        <feature>Спортно окачване</feature>
        <feature>Спортни седалки</feature>
        <feature>Фарове за мъгла</feature>
        <feature>Темпомат</feature>
        <feature>Навигация</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Алфа Ромео</manufacturer_bg>
    <manufacturer_en>Alfa Romeo</manufacturer_en>
    <model generation = "952">Giulia</model>        
    <year_of_production>2016</year_of_production>
    <body_type>Седан</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "6" position="отпред">
            <power units = "конски сили">510</power>
            <torque units = "нютон метри" at="2500об/мин">600</torque>
            <capacity units = "см3">2891</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">8.5</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО6">198</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">3.9</acceleration>
    <maximum_speed units = "км/ч">307</maximum_speed>
    <fuel_tank_volume units = "литри">58</fuel_tank_volume>
    <chassi>
        <front_suspension>двоен напречен носач</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>   
    <number_of_doors>4</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1580</kerb_weight>
    <length units = "мм">4639</length>
    <width units = "мм">1873</width>
    <height units = "мм">1426</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>Круиз контрол</feature>
        <feature>Куатро</feature>
        <feature>Двузонов климатроник</feature>
        <feature>Сензор за дъжд</feature>
        <feature>Спортни седалки</feature>
        <feature>Система - асистент при паркиране</feature>            
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument20.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Пежо</manufacturer_bg>
    <manufacturer_en>Peugeot</manufacturer_en>
    <model generation = "РС" >206</model>        
    <year_of_production>2002</year_of_production>
    <body_type>Хечбек</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position="отпред">
            <power units = "конски сили">177</power>
            <torque units = "нютон метри" at = "4750об/мин">202</torque>
            <capacity units = "см3">1997</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">8.6</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО4">204</emissions>
        </engine>
        <transmission number_of_gears = "5">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">7.5</acceleration>
    <maximum_speed units = "км/ч">220</maximum_speed>
    <fuel_tank_volume units = "литри">50</fuel_tank_volume>
    <chassi>
        <front_suspension>амортисьорна стойка</front_suspension>
        <rear_suspension>торсион</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>3</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1100</kerb_weight>
    <length units = "мм">3835</length>
    <width units = "мм">1673</width>
    <height units = "мм">1430</height>
    <features>
        <feature>Антиблокираща система</feature>                        
        <feature>Климатроник</feature>   
        <feature>Ел. стъкла</feature>
        <feature>Тракшън-контрол</feature>
        <feature>Фарове за мъгла</feature>
        <feature>Имобилайзер</feature>        
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Мазда</manufacturer_bg>
    <manufacturer_en>Mazda</manufacturer_en>
    <model generation = "РХ-8">РХ-8</model>        
    <year_of_production>2003</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position = "отпред">
            <power units = "конски сили">250</power>
            <torque units = "нютон метри" at = "7500об/мин">216</torque>
            <capacity units = "см3">1308</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">11.4</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО3">284</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">6.5</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">61</fuel_tank_volume>
    <chassi>
        <front_suspension>амортисьорна стойка</front_suspension>
        <rear_suspension>винтова пружина</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>4</number_of_doors>
    <number_of_seats>4</number_of_seats>
    <kerb_weight units = "кг.">1345</kerb_weight>
    <length units = "мм">4325</length>
    <width units = "мм">1780</width>
    <height units = "мм">1330</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Мултифункционален волан</feature>
        <feature>Подгряване на волана</feature>
        <feature>Спортно окачване</feature>
        <feature>Климатроник</feature>
        <feature>Вградена система за навигация</feature>
        <feature>Отопление на седалките</feature>
        <feature>Тракшън-контрол</feature>            
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Киа</manufacturer_bg>
    <manufacturer_en>Kia</manufacturer_en>
    <model generation = "2-ра" >Сиид</model>        
    <year_of_production>2013</year_of_production>
    <body_type>Хечбек</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position="отпред">
            <power units = "конски сили">204</power>
            <torque units = "нютон метри" at = "1750об/мин">265</torque>
            <capacity units = "см3">1591</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">7.4</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО5">171</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">7.7</acceleration>
    <maximum_speed units = "км/ч">230</maximum_speed>
    <fuel_tank_volume units = "литри">53</fuel_tank_volume>
    <chassi>
        <front_suspension>винтова пружина</front_suspension>
        <rear_suspension>винтова пружина</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови</rear_brakes>
    </chassi>        
    <number_of_doors>3</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1448</kerb_weight>
    <length units = "мм">4310</length>
    <width units = "мм">1780</width>
    <height units = "мм">1430</height>
    <features>
        <feature>Антиблокираща система</feature>                        
        <feature>Климатроник</feature>       
        <feature>Спортни седалки</feature>
        <feature>Парктроник</feature>
        <feature>Отопление на седалките</feature>
        <feature>Темпомат</feature>
        <feature>Навигация</feature>
        <feature>Сензор за дъжд</feature>
        <feature>Светлини за завиване</feature>
        <feature>Фарове за мъгла</feature>
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument19.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Ферари</manufacturer_bg>
    <manufacturer_en>Ferrari</manufacturer_en>
    <model generation = "Енцо" >Енцо</model>        
    <year_of_production>2002</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "12" position="отзад">
            <power units = "конски сили">660</power>
            <torque units = "нютон метри" at = "5500об/мин">657</torque>
            <capacity units = "см3">5998</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">23</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО4">545</emissions>
        </engine>
        <transmission number_of_gears = "6">ръчна</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">3.65</acceleration>
    <maximum_speed units = "км/ч">350</maximum_speed>
    <fuel_tank_volume units = "литри">110</fuel_tank_volume>
    <chassi>
        <front_suspension>двоен напречен носач</front_suspension>
        <rear_suspension>двоен напречен носач</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>        
    <number_of_doors>2</number_of_doors>
    <number_of_seats>2</number_of_seats>
    <kerb_weight units = "кг.">1365</kerb_weight>
    <length units = "мм">4702</length>
    <width units = "мм">2035</width>
    <height units = "мм">1147</height>
    <features>
        <feature>Антиблокираща система</feature>                        
        <feature>Серво управление</feature>                        
        <feature>Имобилайзер</feature>           
        <feature>Мултифункционален волан</feature>
        <feature>Електрически странични огледала</feature>
        <feature>Електронна система за стабилизация</feature>        
    </features>        
</car>

=== andrei-1995/ASP.Net---Fmi-project/Cars/Cars/Xmls/XMLDocument13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE car SYSTEM "..\Cars.dtd">
<car>
    <manufacturer_bg>Сеат</manufacturer_bg>
    <manufacturer_en>Seat</manufacturer_en>
    <model generation = "3-та">Леон Купра</model>        
    <year_of_production>2016</year_of_production>
    <body_type>Купе</body_type>
    <powertrain>
        <engine fuel = "бензин" number_of_cylinders = "4" position="отпред">
            <power units = "конски сили">290</power>
            <torque units = "нютон метри" at="1700-5800об/мин">350</torque>
            <capacity units = "см3">1984</capacity>
            <consumption units = "литри/100 км." type = "комбиниран">6.5</consumption>
            <emissions units = "грама CO2/км." class = "ЕВРО6">149</emissions>
        </engine>
        <transmission number_of_gears = "6">автоматична</transmission>
    </powertrain>
    <acceleration units = "секунди" type = "0-100км/ч">5.7</acceleration>
    <maximum_speed units = "км/ч">250</maximum_speed>
    <fuel_tank_volume units = "литри">50</fuel_tank_volume>
    <chassi>
        <front_suspension>независимо пружинно тип McPherson със стабилизатор</front_suspension>
        <rear_suspension>многолостово независимо окачване</rear_suspension>
        <front_brakes>дискови вентилирани</front_brakes>
        <rear_brakes>дискови вентилирани</rear_brakes>
    </chassi>   
    <number_of_doors>3</number_of_doors>
    <number_of_seats>5</number_of_seats>
    <kerb_weight units = "кг.">1320</kerb_weight>
    <length units = "мм">4236</length>
    <width units = "мм">1810</width>
    <height units = "мм">1423</height>
    <features>
        <feature>Антиблокираща система</feature>
        <feature>Тракшън контрол</feature>
        <feature>Спортно окачване</feature>
        <feature>Старт/Стоп система</feature>
        <feature>Климатроник</feature>
        <feature>Сензор за дъжд</feature>
        <feature>Спортни седалки</feature>
        <feature>Сензори за паркиране</feature>
        <feature>Отопление на седалките</feature>
        <feature>Сензор за дъжд</feature>        
    </features>        
</car>
